### ISSUE TITLE
Require Empty Hand

### ISSUE THREAD

**Issue by brisingraerowing** [crazysnailboy/VillagerInventory#2]
Could you add a config option to require an empty hand to view a villager's inventory? As it is, this mod interferes with putting villagers into a Random Things Summoning Pendulum to transport them somewhere else, as that requires a shift-right-click as well.

**Comment by crazysnailboy** [comment]
Hey, yes I'll add that in. Thanks for the suggestion!

**Comment by crazysnailboy** [comment]
Hi,

I've uploaded v1.1 which includes this change. Please could you let me know whether that works for you?

[v1.1 for Minecraft 1.11.x](https://github.com/crazysnailboy/VillagerInventory/releases/download/v1.11-1.1/VillagerInventory-1.11-1.1.jar)
[v1.1 for Minecraft 1.10.2](https://github.com/crazysnailboy/VillagerInventory/releases/download/v1.10.2-1.1/VillagerInventory-1.10.2-1.1.jar)

Thanks

**Comment by brisingraerowing** [comment]
I'll take a look at it and see.

**Comment by crazysnailboy** [comment]
So.. did it work?

**Comment by brisingraerowing** [comment]
I forgot about this. I'll check now.

**Comment by brisingraerowing** [comment]
I just realized I need to update the mod (I have 1.0.1) 🤦

I'll do that and get back to you.

**Comment by brisingraerowing** [comment]
It works! 😎

**Comment by crazysnailboy** [comment]
Thanks for letting me know :)
